name: namaz_timing_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  flutter_screenutil: ^5.9.2

  shared_preferences: ^2.2.3
  connectivity_plus: ^4.0.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/audio/
    - assets/icons/
    - assets/images/
    - assets/lottie/

  fonts:
    - family: OpenSansRegular
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf